markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
url: http://cb.platan.us
name: CÃ³digo Banana
description: El blog oficial de Platanus
paginate: 8
remote_layout_url: http://platan.us/blog-assets
remote_layouts:
    - default
    - post/jaime-bunzli
    - post/leandro-segovia
    - post/emilio-blanco
    - post/felipe-campos
    - post/andres-arellano
    - post/juan-ignacio-donoso
    - post/ignacio-baixas
    - post/agustin-feuerhake
